# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      timezone: "Australia/Sydney"
    commit-message:
      prefix: "[Dependabot]"
      include: "scope"
    open-pull-requests-limit: 8
    reviewers:
      - "danascheider"
    versioning-strategy: "increase"
    # All packages published by the Storybook maintainers should be updated
    # together using `npx storybook@latest upgrade && yarn dedupe`. Updates
    # are issued very frequently so this should be done once a week or so.
    ignore:
      - dependency-name: "storybook"
      - dependency-name: "@storybook/addon-actions"
      - dependency-name: "@storybook/addon-essentials"
      - dependency-name: "@storybook/addon-interactions"
      - dependency-name: "@storybook/addon-links"
      - dependency-name: "@storybook/addon-mdx-gfm"
      - dependency-name: "@storybook/cli"
      - dependency-name: "@storybook/react"
      - dependency-name: "@storybook/react-vite"
