name: Skyrim Inventory Management Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "19.8.1"
    - name: Install Node Modules
      run: yarn
    - name: lint
      run: yarn lint
    - name: format
      run: yarn format
    - name: Run tests
      run: yarn test
