name: Skyrim Inventory Management Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node Modules
      run: yarn
    - name: lint
      run: yarn lint
    - name: format
      run: yarn format
    - name: Run tests
      env:
        VITE_FIREBASE_API_KEY: '${{ secrets.VITE_FIREBASE_API_KEY }}'
        VITE_FIREBASE_AUTH_DOMAIN: skyrim-inventory-management.firebaseapp.com
        VITE_FIREBASE_PROJECT_ID: skyrim-inventory-management
        VITE_FIREBASE_STORAGE_BUCKET: skyrim-inventory-management.appspot.com
        VITE_FIREBASE_MESSAGING_SENDER_ID: '${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}'
        VITE_FIREBASE_APP_ID: '${{ secrets.VITE_FIREBASE_APP_ID }}'
      run: yarn test
